name: Playwright Tests

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18" # Or your preferred Node.js version
      - name: Install dependencies
        run: npm install # Or use yarn install if you use Yarn
        working-directory: FlaskSurveyForm
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: FlaskSurveyForm
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: FlaskSurveyForm
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: FlaskSurveyForm/test-results/
          retention-days: 30
