name: Playwright Tests

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [main]

jobs:
  e2e-tests: # Renamed job
    timeout-minutes: 60 # Kept timeout
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v4 # Updated checkout action version

      # Node setup is handled by playwright-github-action
      # Dependency and browser installation is handled by playwright-github-action
      - uses: microsoft/playwright-github-action@v1
        # This action installs Node, dependencies (npm install), and Playwright browsers

      - name: Run Playwright tests # Simplified step name
        run: npx playwright test # Use npx playwright test directly
        working-directory: FlaskSurveyForm # Specify working directory

      - uses: actions/upload-artifact@v4 # Re-added artifact upload
        if: always()
        with:
          name: playwright-report
          path: FlaskSurveyForm/test-result/ # Adjusted path for report location
          retention-days: 30 # Set retention days for artifacts
